### ISSUE TITLE
Something wrong with featureCounts

### ISSUE THREAD

**Issue by Jenny-chen98** [vivekbhr/Subread_to_DEXSeq#11]
Hi,
firstly, thanks for your wonderful scripts.

I'm trying to use  dexseq_prepare_annotation2.py to prepare the needed GTF for featureCounts and DEXSeq, my primary GTF file is Homo_sapiens.GRCh37.75.gtf which downloaded from ensembl.Then, This step is running successfully whithout any error.

However, when I ran featureCounts, something wrong happened, WARNING was reported as follow:
![image](https://user-images.githubusercontent.com/59354090/99671349-e33b7c00-2aac-11eb-9b79-6c86825429a9.png)

I wonder if this mistake gets in the way? Will it affect the subsequent analysis? Since my subsequent analysis also reported errors, I don't know what went wrong.

` dxd.fc <- DEXSeqDataSetFromFeatureCounts("~/dexseq/test_out3.txt",flattenedfile = "~/annotation/GRCh37_feature.gtf",sampleData = samp)`

> Reading and adding Exon IDs for DEXSeq
> Error in DEXSeqDataSetFromFeatureCounts("\~/dexseq/test_out3.txt", flattenedfile = "~/annotation/GRCh37_feature.gtf", :
>  Count files do not correspond to the flattened annotation file
> 此外: Warning message:
> 1 aggregate geneIDs were found truncated in featureCounts outpu

Thanks
Jessian

**Comment by vivekbhr** [comment]
Hi Jessian

So the featurecounts warning is because featurecounts truncates gene names longer than 256 characters to 256. It only creates a problem when you want to merge your DEXseq output back to original GTF. You can either ignore these exons (they are only a couple) or cut your GTF names to 256 to match the DEXseq output.

Best,
Vivek
