### ISSUE TITLE
Subread_to_DEXseq problem

### ISSUE THREAD

**Issue by NicolasHipp** [vivekbhr/Subread_to_DEXSeq#8]
Hi,

I'm trying to use your program in order to use featureCount as input for DEXseq, but I'm facing some troubles with it.

I'm working with Homo_sapiens.GRCh38.91.chr.gtf release from ensembl

![capture d ecran 2018-05-23 a 15 08 57](https://user-images.githubusercontent.com/18481923/40426411-4dbfeaba-5e9b-11e8-930c-773545a1bf80.png)

I followed the tutorial, as I am on mac, I modify the dexseq_prepare_annotation2.py, by adding a .bak after 'sed -i.....' -> 'sed -i.bak....' at the end of the script to do not have error during the GTF preparation. 
So I used the following command : 

![capture d ecran 2018-05-23 a 15 19 54](https://user-images.githubusercontent.com/18481923/40426995-c6dc24bc-5e9c-11e8-9fa2-e0c6c5d53d9b.png)

And after that start to use featureCounts-1.6

<img width="996" alt="capture d ecran 2018-05-23 a 15 16 40" src="https://user-images.githubusercontent.com/18481923/40426840-57e35922-5e9c-11e8-9ec5-aa3222c1b58d.png">

As you can see, featureCounts doesn't support the GTF file that generate the script. Do you have any idea what's going wrong with this procedure ?

Thanks for the help, and the tutorial
Nicolas

**Comment by vivekbhr** [comment]
could you try using `-t exonic_part` in the featurecounts command? actually I think you're providing the other GTF as input. the GTF obtained as output of `-f` command should be used

**Comment by vivekbhr** [comment]
@NicolasHipp  any follow up on that?

**Comment by NicolasHipp** [comment]
Oh sorry, I didn't see the answer. 
I'm back in this project at the end of hollidays, I will update this post after trying your solution.

Thanks and sorry for this late answer,
nicolas

**Comment by vivekbhr** [comment]
No update on this.? Just to confirm, the default featurecounts run would use "exon" as the feature name, same would be expected by the R script later. The file you get from `dexseq_prepare_annotation2.py` already contain this so It should be ok. Just use the `-f` option.

**Comment by marvel64** [comment]
Hello,
Thanks for the scripts! I am running into a related issue.

1. I generated the flattened GTF per instructions.

`Homo_sapiens.GRCh38.82.filtered.flat.gtf`

<img width="1222" alt="Screen Shot 2019-04-09 at 9 55 49 PM" src="https://user-images.githubusercontent.com/1090101/55846952-8b3d4500-5b15-11e9-8817-f355185457c9.png">

2. Read counting needs the `-f exonic_part` as  in your reply from May 26, 2018, otherwise it will return the same error listed in the original post.  However, this works fine.
```
featureCounts -f -O -s 2 -p -T 4 -t exonic_part \
-F GTF -a Homo_sapiens.GRCh38.82.filtered.flat.gtf \
-o exon_count.txt *.bam
```

Now:
3. Importing the `exon_count.txt` matrix into R using the `load_SubreadOutput.R` script will give me an error message

```
dxd = DEXSeqDataSetFromFeatureCounts("Data/exon_count.txt",
				     flattenedfile = "~/Homo_sapiens.GRCh38.82.filtered.flat.gtf",
				     sampleData = samp)

Reading and adding Exon IDs for DEXSeq
Error in DEXSeqDataSetFromFeatureCounts("Data/exon_count.txt", flattenedfile = "~/Homo_sapiens.GRCh38.82.filtered.flat.gtf",  :
  Count files do not correspond to the flattened annotation file
```

Troubleshooting so far (?using a different/old exon_count.txt file from a previous run etc.) so far did not result in any obvious mistake. I will continue to look into it but maybe you spot an obvious mistake or can help clarify. Much appreciated.

```
Run on macOS 10.14.4
featureCounts 1.6.1
R 3.5.3
```

**Comment by ChristianRohde** [comment]
I downloaded Homo_sapiens.GRCh38.101.gtf from ENSEMBLE and used Subread_to_DEXSeq-master/dexseq_prepare_annotation2.py with python2.7 to create a flattened GTF. Next I run featureCounts from subread v2.0.1 (conda with python 3.8) without problems. When I tried to reformat and upload data to DEXSeq I always got the error: Count files do not correspond to the flattened annotation file! I inspected the load_SubreadOutput.R script and finally realized that under my conditions the max(nchar(featureCounts_IDs)) were actually 254. And all IDs which could not be found in the flattened GTF file after restructuring the IDs had this length. Trimming  to 255 in this case obviously did not help. Changing the script to "aggregates$gene_id <- substr(aggregates$gene_id,1,max(nchar(id)))" helped me to overcome this problem.

**Comment by vivekbhr** [comment]
Hi @ChristianRohde yes that's correct. Featurecounts clips the gene names to 256 chars and that causes the mismatch between the count table and the annotation table. i usually remove these long gene names form the resulting GTF (they are almost always multi-genic exons so removing them doesn't affect the analysis much), this fixes the problem for me.

**Comment by liqianqian-123** [comment]
I'm facing some troubles when using featurecount for DEXseq:
I have generated the required GTF file and expression matrix file, but an error was reported when I introduced it through DEXSeqDataSetFromHTSeq：
> dxd.fc <- DEXSeqDataSetFromFeatureCounts("affinis_count.txt",
+                                          flattenedfile = "affinis.gff",sampleData = samp)
Reading and adding Exon IDs for DEXSeq
Error in DEXSeqDataSetFromFeatureCounts("affinis_count.txt", flattenedfile = "affinis.gff",  : 
  Count files do not correspond to the flattened annotation file
In addition: Warning message:
0 aggregate geneIDs were found truncated in featureCounts output 

Next, I will put all the processes below
##
python /home/students/tools/Subread_to_DEXSeq/dexseq_prepare_annotation2.py -f affinis.gtf /home/students/0_database/1_affinis_genemo_hisat2/affinis.genomic.gtf affinis.gff
##count
featureCounts -f -O -s 2 -p -T 8 -F GTF -a affinis.gtf -o affinis_count.txt /home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/*.bam 
###note: BAM files are generated by hisat2
hisat2 -t -p 20 --new-summary --summary-file 190505.log -x /home/students/0_database/1_affinis_genemo_hisat2/affinis.genomic -1 /home/students/3_qqli/him_hainan_mRNA/clean_reads/minlength_50_trimmomatic/190505_1_paired.gz -2 /home/students/3_qqli/him_hainan_mRNA/clean_reads/minlength_50_trimmomatic/190505_2_paired.gz | samtools sort -@ 20 -n -o 190505.bam

###R
source("load_SubreadOutput.R")
samp <- data.frame(row.names = c("Hai-05","Hai-16","Hai-19","Hai-20","Him-12","Him-13","Him-35","Him-36"), 
                        condition = rep(c("hainanus","himalayanus"),each=4))
						

dxd.fc <- DEXSeqDataSetFromFeatureCounts("affinis_count.txt",
                                         flattenedfile = "affinis.gtf",sampleData = samp)


Reading and adding Exon IDs for DEXSeq
Error in DEXSeqDataSetFromFeatureCounts("affinis_count.txt", flattenedfile = "affinis.gff",  : 
  Count files do not correspond to the flattened annotation file
In addition: Warning message:
0 aggregate geneIDs were found truncated in featureCounts output

There is no error in the file generation process,  and I pasted the first few lines of the GTF file and the expression matrix file below, I checked the number of exons in the expression matrix and exonic_part_number in the GTF. The number of numbers is the same, but the problem seems to be that the two files do not correspond. And I modified load_SubreadOutput.R script:  "aggregates $gene_ ID < - substr (aggregates $gene_id, 1, max (nchar (ID)) ", still the same problem. I don't know where the problem is. Can you help me? Thank you very much!
#######matrix
# Program:featureCounts v2.0.1; Command:"featureCounts" "-f" "-O" "-s" "2" "-p" "-T" "8" "-F" "GTF" "-a" "affinis.gtf" "-o" "affinis_count.txt" "/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/190505.bam" "/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/190516.bam" "/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/190519.bam" "/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/190520.bam" "/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/20201012.bam" "/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/20201013.bam" "/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/20201035.bam" "/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/20201036.bam" 
Geneid	Chr	Start	End	Strand	Length	/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/190505.bam	/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/190516.bam	/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/190519.bam	/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/190520.bam	/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/20201012.bam	/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/20201013.bam	/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/20201035.bam	/home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/20201036.bam
Parent=evm.model.Contig1.1	Contig1	82977	82982	+	6	0	0	5	1	0	0	7	0
Parent=evm.model.Contig1.1	Contig1	84818	84934	+	117	0	0	5	1	0	2	13	0
Parent=evm.model.Contig1.1	Contig1	85276	85374	+	99	0	0	6	1	0	3	17	0
Parent=evm.model.Contig1.1	Contig1	85954	86096	+	143	0	0	11	0	1	3	24	0
Parent=evm.model.Contig1.1	Contig1	86527	86665	+	139	2	0	11	1	0	1	21	0
Parent=evm.model.Contig1.1	Contig1	90369	90512	+	144	1	0	4	1	1	2	15	3
Parent=evm.model.Contig1.1	Contig1	91229	91965	+	737	1	5	21	11	3	2	52	4
Parent=evm.model.Contig1.1	Contig1	94213	94465	+	253	1	5	6	6	5	3	23	2

  ########GTF
Contig1	dexseq_prepare_annotation2.py	aggregate_gene	82977	99686	.	+	.	gene_id "Parent=evm.model.Contig1.1"
Contig1	dexseq_prepare_annotation2.py	exonic_part	82977	82982	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "001"
Contig1	dexseq_prepare_annotation2.py	exonic_part	84818	84934	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "002"
Contig1	dexseq_prepare_annotation2.py	exonic_part	85276	85374	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "003"
Contig1	dexseq_prepare_annotation2.py	exonic_part	85954	86096	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "004"
Contig1	dexseq_prepare_annotation2.py	exonic_part	86527	86665	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "005"
Contig1	dexseq_prepare_annotation2.py	exonic_part	90369	90512	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "006"
Contig1	dexseq_prepare_annotation2.py	exonic_part	91229	91965	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "007"
